#!/usr/bin/env python3
"""
Export agent2_output section_*.md files to a single Word document (.docx).

Reads section_*.md in SECTIONS order, parses markdown, and writes prospectus-draft.docx.

Usage:
  python export_docx.py [--output-dir agent2_output]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# Section order (must match agent2.py SECTIONS)
SECTIONS = [
    ("ExpectedTimetable", "Expected Timetable"),
    ("Contents", "Contents"),
    ("Summary", "Summary"),
    ("Definitions", "Definitions"),
    ("Glossary", "Glossary of Technical Terms"),
    ("ForwardLooking", "Forward-Looking Statements"),
    ("RiskFactors", "Risk Factors"),
    ("Waivers", "Waivers from Strict Compliance with Listing Rules (Waivers and Exemptions)"),
    ("InfoProspectus", "Information about this Prospectus and the Global Offering"),
    ("DirectorsParties", "Directors and Parties Involved in the Global Offering"),
    ("CorporateInfo", "Corporate Information"),
    ("Regulation", "Regulation (Regulatory Overview)"),
    ("IndustryOverview", "Industry Overview"),
    ("HistoryReorg", "History, Reorganization, and Corporate Structure"),
    ("Business", "Business"),
    ("ContractualArrangements", "Contractual Arrangements (Variable Interest Entities)"),
    ("ControllingShareholders", "Relationship with Our Controlling Shareholders"),
    ("ConnectedTransactions", "Connected Transactions"),
    ("DirectorsSeniorMgmt", "Directors and Senior Management"),
    ("SubstantialShareholders", "Substantial Shareholders"),
    ("ShareCapital", "Share Capital"),
    ("FinancialInfo", "Financial Information"),
    ("UseOfProceeds", "Future Plans and Use of Proceeds"),
    ("Underwriting", "Underwriting"),
    ("GlobalOfferingStructure", "Structure of the Global Offering"),
]


def find_section_file(out_path: Path, section_id: str, section_name: str) -> Path | None:
    """Find section_*.md file for this section."""
    safe_name = section_name.replace(" ", "_").replace("&", "and")
    pattern = f"section_{section_id}_{safe_name}.md"
    candidate = out_path / pattern
    if candidate.exists():
        return candidate
    for f in out_path.glob(f"section_{section_id}_*.md"):
        return f
    return None


def add_markdown_to_document(doc, text: str) -> None:
    """Parse markdown text and add to docx document."""
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("# "):
            doc.add_heading(line[2:].strip(), level=0)
            i += 1
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=1)
            i += 1
        elif line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=2)
            i += 1
        elif line.strip() == "":
            i += 1
        else:
            # Collect paragraph (until blank or next heading)
            parts: list[str] = []
            while i < len(lines) and lines[i].strip() != "" and not lines[i].startswith("#"):
                parts.append(lines[i])
                i += 1
            if parts:
                para_text = "\n".join(parts)
                _add_formatted_paragraph(doc, para_text)


def _add_formatted_paragraph(doc, text: str) -> None:
    """Add a paragraph with **bold** and *italic* support."""
    para = doc.add_paragraph()
    pattern = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*|[^*\n]+|\n)")
    for m in pattern.finditer(text):
        s = m.group(0)
        if s == "\n":
            para.add_run(" ")
        elif s.startswith("**") and s.endswith("**"):
            run = para.add_run(s[2:-2])
            run.bold = True
        elif s.startswith("*") and s.endswith("*") and len(s) > 1:
            run = para.add_run(s[1:-1])
            run.italic = True
        else:
            para.add_run(s)


def run_export(output_dir: str | Path = "agent2_output") -> Path:
    """Read section_*.md, combine into .docx, return path to output file."""
    try:
        from docx import Document
    except ImportError:
        raise ImportError(
            "python-docx not installed. Run: pip install python-docx"
        ) from None

    out_path = Path(output_dir)
    if not out_path.exists():
        raise FileNotFoundError(f"Output dir not found: {out_path}")

    doc = Document()
    doc.add_heading("Prospectus Draft", level=0)
    doc.add_paragraph("Generated by Agent2 pipeline.")

    added = 0
    for section_id, section_name in SECTIONS:
        section_file = find_section_file(out_path, section_id, section_name)
        if not section_file:
            continue
        content = section_file.read_text(encoding="utf-8")
        # Skip first line (# Section X: Name) - we add our own heading
        lines = content.split("\n")
        body_lines: list[str] = []
        for i, ln in enumerate(lines):
            if i == 0 and ln.startswith("# "):
                continue
            body_lines.append(ln)

        doc.add_page_break()
        doc.add_heading(f"Section {section_id}: {section_name}", level=1)
        add_markdown_to_document(doc, "\n".join(body_lines))
        added += 1

    if added == 0:
        raise FileNotFoundError("No section_*.md files found in " + str(out_path))

    output_file = out_path / "prospectus-draft.docx"
    doc.save(output_file)
    print(f"Saved: {output_file}")
    return output_file


def main() -> None:
    parser = argparse.ArgumentParser(description="Export section_*.md to Word (.docx)")
    parser.add_argument(
        "--output-dir",
        default="agent2_output",
        help="Directory containing section_*.md files",
    )
    args = parser.parse_args()
    run_export(args.output_dir)


if __name__ == "__main__":
    main()
