"""
Default alias strings -> canonical **section** ids (underscore slugs).

Expand via :meth:`TitleNormalizer.register_alias`.
"""

from __future__ import annotations

# alias_lower -> canonical_section_id
DEFAULT_SECTION_ALIASES: dict[str, str] = {
    # User examples + common HK prospectus variants
    "our business": "Business",
    "the business": "Business",
    "business": "Business",
    "history and development": "History_Reorganization_Corporate_Structure",
    "history, reorganization and corporate structure": "History_Reorganization_Corporate_Structure",
    "history reorganization and corporate structure": "History_Reorganization_Corporate_Structure",
    "operating and financial review": "Financial_Information",
    "financial information": "Financial_Information",
    "use of proceeds": "Future_Plans_and_Use_of_Proceeds",
    "future plans and use of proceeds": "Future_Plans_and_Use_of_Proceeds",
    "global offering": "Structure_of_the_Global_Offering",
    "structure of the global offering": "Structure_of_the_Global_Offering",
    "regulations": "Regulatory_Overview",
    "regulation": "Regulatory_Overview",
    "regulatory overview": "Regulatory_Overview",
    "industry": "Industry_Overview",
    "industry overview": "Industry_Overview",
    "risk factors": "Risk_Factors",
    "principal risks": "Risk_Factors",
    "summary": "Summary",
    "definitions": "Definitions",
    "glossary": "Glossary_of_Technical_Terms",
    "glossary of technical terms": "Glossary_of_Technical_Terms",
    "forward-looking statements": "Forward_Looking_Statements",
    "waivers": "Waivers_and_Exemptions",
    "waivers from strict compliance with listing rules": "Waivers_and_Exemptions",
    "waivers from strict compliance with listing rules (waivers and exemptions)": "Waivers_and_Exemptions",
    "underwriting": "Underwriting",
    "connected transactions": "Connected_Transactions",
    "substantial shareholders": "Substantial_Shareholders",
    "share capital": "Share_Capital",
    "how to apply for hong kong offer shares": "How_to_Apply_for_Hong_Kong_Offer_Shares",
    "how to apply": "How_to_Apply_for_Hong_Kong_Offer_Shares",
    "appendices": "Appendices",
    "expected timetable": "Expected_Timetable",
    "contents": "Contents",
    # Front / back matter + extras observed in HKEX corpus.
    "cover": "Cover",
    "cover page": "Cover",
    "back cover": "Back_Cover",
    "backcover": "Back_Cover",
    "important": "Important_Notice",
    "important notice": "Important_Notice",
    "cornerstone investors": "Cornerstone_Investors",
    "cornerstone investor": "Cornerstone_Investors",
    "our cornerstone investors": "Cornerstone_Investors",
    "cornerstone investment": "Cornerstone_Investors",
    "cornerstone investments": "Cornerstone_Investors",
    "structured contracts": "Contractual_Arrangements_VIE",
    "responsibility statements": "Important_Notice",
    "responsibility statement": "Important_Notice",
    # Common regional / style variants
    "reorganisation": "History_Reorganization_Corporate_Structure",
    "reorganization": "History_Reorganization_Corporate_Structure",
    "history and corporate structure": "History_Reorganization_Corporate_Structure",
    "history, development and corporate structure": "History_Reorganization_Corporate_Structure",
    "corporate structure and history": "History_Reorganization_Corporate_Structure",
    "continuing connected transaction": "Connected_Transactions",
    "continuing connected transactions": "Connected_Transactions",
    "related party transactions": "Connected_Transactions",
    "regulation and supervision": "Regulatory_Overview",
    "regulatory environment": "Regulatory_Overview",
    "relationship with the controlling shareholders": "Relationship_with_Controlling_Shareholders",
    "relationship with our controlling shareholder": "Relationship_with_Controlling_Shareholders",
    "directors, supervisors and senior management": "Directors_and_Senior_Management",
    "directors, supervisors and parties involved in the global offering": "Parties_Involved_in_the_Global_Offering",
    "waivers from strict compliance with the listing rules": "Waivers_and_Exemptions",
    "waivers and exemption": "Waivers_and_Exemptions",
    "waivers and exemptions": "Waivers_and_Exemptions",
    "glossary of terms": "Glossary_of_Technical_Terms",
    "contractual arrangement": "Contractual_Arrangements_VIE",
    "contractual arrangements": "Contractual_Arrangements_VIE",
    "relationship with byd group": "Relationship_with_Controlling_Shareholders",
    "relationship with the byd group": "Relationship_with_Controlling_Shareholders",
}


# Regex fallback rules. Each (pattern, canonical_id) is applied on the normalized title
# AFTER exact/alias lookup fails but BEFORE fuzzy matching. Useful for open-ended
# series like "APPENDIX I — ACCOUNTANTS' REPORT" where the punctuation / numeral varies.
import re as _re

DEFAULT_SECTION_ALIAS_REGEX: list[tuple["_re.Pattern[str]", str]] = [
    (_re.compile(r"^appendix\b", _re.I), "Appendices"),
    (_re.compile(r"^annex\b", _re.I), "Appendices"),
    (_re.compile(r"^schedule\b", _re.I), "Appendices"),
    (_re.compile(r"^exhibit\b", _re.I), "Appendices"),
    (_re.compile(r"^risk factor", _re.I), "Risk_Factors"),
    (_re.compile(r"^forward[\s-]?looking", _re.I), "Forward_Looking_Statements"),
    (_re.compile(r"^(our\s+)?business\b", _re.I), "Business"),
    (_re.compile(r"^industry\b", _re.I), "Industry_Overview"),
    (_re.compile(r"^regulat", _re.I), "Regulatory_Overview"),
    (_re.compile(r"^history,?\s", _re.I), "History_Reorganization_Corporate_Structure"),
    (_re.compile(r"^substantial\s+shareholder", _re.I), "Substantial_Shareholders"),
    (_re.compile(r"^relationship\s+with", _re.I), "Relationship_with_Controlling_Shareholders"),
    (_re.compile(r"^(continuing\s+)?connected\s+transaction", _re.I), "Connected_Transactions"),
    (_re.compile(r"^directors?\b", _re.I), "Directors_and_Senior_Management"),
    (_re.compile(r"^share\s+capital", _re.I), "Share_Capital"),
    (_re.compile(r"^financial\s+information", _re.I), "Financial_Information"),
    (_re.compile(r"^future\s+plans", _re.I), "Future_Plans_and_Use_of_Proceeds"),
    (_re.compile(r"^use\s+of\s+proceeds", _re.I), "Future_Plans_and_Use_of_Proceeds"),
    (_re.compile(r"^underwrit", _re.I), "Underwriting"),
    (_re.compile(r"^structure\s+of\s+the\s+global\s+offering", _re.I), "Structure_of_the_Global_Offering"),
    (_re.compile(r"^how\s+to\s+apply", _re.I), "How_to_Apply_for_Hong_Kong_Offer_Shares"),
    (_re.compile(r"^corporate\s+information", _re.I), "Corporate_Information"),
    (_re.compile(r"^waivers?\b", _re.I), "Waivers_and_Exemptions"),
    (_re.compile(r"^information\s+about\s+this\s+prospectus", _re.I), "Prospectus_and_Global_Offering_Information"),
    (_re.compile(r"^cornerstone\s+investor", _re.I), "Cornerstone_Investors"),
    (_re.compile(r"^important\b", _re.I), "Important_Notice"),
    (_re.compile(r"^(back\s?cover|back\s+cover)$", _re.I), "Back_Cover"),
    (_re.compile(r"^cover\b", _re.I), "Cover"),
    (_re.compile(r"^contractual\s+arrangement", _re.I), "Contractual_Arrangements_VIE"),
    (_re.compile(r"^parties\s+involved", _re.I), "Parties_Involved_in_the_Global_Offering"),
    (_re.compile(r"^glossary", _re.I), "Glossary_of_Technical_Terms"),
    (_re.compile(r"^definitions", _re.I), "Definitions"),
    (_re.compile(r"^summary", _re.I), "Summary"),
    (_re.compile(r"^expected\s+timetable", _re.I), "Expected_Timetable"),
    (_re.compile(r"^contents$", _re.I), "Contents"),
]
