// GET /api/agent2/export/docx - Export all_sections.md to Word (.docx)
// Uses docx npm package - no Python spawn, fast in-process export
import { NextResponse } from "next/server";
import path from "path";
import fs from "fs/promises";
import {
  Document,
  Paragraph,
  TextRun,
  PageBreak,
  Packer,
  HeadingLevel,
} from "docx";
import { getProspectusRoot } from "@/lib/prospectus-root";
import { stripVerificationNotes } from "@/lib/draft-cleaning";

export const runtime = "nodejs";
export const maxDuration = 60;

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = [];
  let i = 0;
  const n = text.length;
  while (i < n) {
    if (text.slice(i, i + 2) === "**") {
      const end = text.indexOf("**", i + 2);
      if (end >= 0) {
        runs.push(new TextRun({ text: text.slice(i + 2, end), bold: true }));
        i = end + 2;
        continue;
      }
    }
    if (text[i] === "*" && text[i + 1] !== "*") {
      const end = text.indexOf("*", i + 1);
      if (end >= 0) {
        runs.push(new TextRun({ text: text.slice(i + 1, end), italics: true }));
        i = end + 1;
        continue;
      }
    }
    if (text[i] === "\n") {
      runs.push(new TextRun({ text: " " }));
      i++;
      continue;
    }
    let j = i;
    while (j < n && text[j] !== "*" && text[j] !== "\n") j++;
    if (j > i) {
      runs.push(new TextRun({ text: text.slice(i, j) }));
      i = j;
      continue;
    }
    runs.push(new TextRun({ text: text[i] }));
    i++;
  }
  return runs;
}

function markdownToDocxChildren(md: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = md.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(4).trim(),
          heading: HeadingLevel.HEADING_2,
        })
      );
      i++;
    } else if (line.startsWith("#### ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(5).trim(),
          heading: HeadingLevel.HEADING_3,
        })
      );
      i++;
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(3).trim(),
          heading: HeadingLevel.HEADING_1,
        })
      );
      i++;
    } else if (line.trim() === "") {
      i++;
    } else {
      const parts: string[] = [];
      while (i < lines.length && lines[i].trim() !== "" && !lines[i].startsWith("#")) {
        parts.push(lines[i]);
        i++;
      }
      if (parts.length > 0) {
        const paraText = parts.join("\n");
        const runs = parseInlineFormatting(paraText);
        if (runs.length > 0) {
          paragraphs.push(new Paragraph({ children: runs }));
        }
      }
    }
  }
  return paragraphs;
}

export async function GET() {
  try {
    const root = getProspectusRoot();
    const draftPath = path.join(root, "agent2_output", "all_sections.md");

    let content: string;
    try {
      content = await fs.readFile(draftPath, "utf8");
    } catch {
      return NextResponse.json(
        { error: "No draft found. Run Agent2 to generate sections first." },
        { status: 404 }
      );
    }

    if (
      !content ||
      content.includes("(Your generated prospectus will appear here.)")
    ) {
      return NextResponse.json(
        { error: "Draft is empty. Generate sections first." },
        { status: 404 }
      );
    }

    content = stripVerificationNotes(content);

    const children: Paragraph[] = [];

    children.push(
      new Paragraph({
        text: "Prospectus Draft",
        heading: HeadingLevel.TITLE,
      }),
      new Paragraph({ text: "Generated by Agent2 pipeline." })
    );

    const blocks = content.split(/\n## /);
    for (let idx = 1; idx < blocks.length; idx++) {
      const block = blocks[idx];
      const firstLineEnd = block.indexOf("\n");
      const firstLine =
        firstLineEnd >= 0 ? block.slice(0, firstLineEnd).trim() : block.trim();
      const sectionBody =
        firstLineEnd >= 0 ? block.slice(firstLineEnd + 1).trim() : "";
      const sectionTitle = firstLine.replace(/^Section [^:]+: /, "").trim();

      if (!sectionTitle && !sectionBody) continue;

      children.push(new Paragraph({ children: [new PageBreak()] }));
      children.push(
        new Paragraph({
          text: sectionTitle,
          heading: HeadingLevel.HEADING_1,
        })
      );
      children.push(...markdownToDocxChildren(sectionBody));
    }

    const doc = new Document({
      sections: [
        {
          properties: {},
          children,
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const filename = `prospectus-draft-${new Date().toISOString().slice(0, 10)}.docx`;

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": String(buffer.length),
      },
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Server error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
